kanbanapi:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - .:/kanban-api
  links:
    - mongo
  environment:
    - DATABASE_URL=mongodb://mongo:27017/local
    - SECRET='testsecret'
mongo:
  image: mongo
  ports:
    - "27017"
